### PR TITLE
#34: update readme for all

### PR DESCRIPTION
**Pull request by tarekait1996**
*update readme for all

### CODE REVIEW

**Comment by narrapangan** [comment]
Looks good!

**Comment by superDeano** [comment]
You forgot someone.

**Comment by narrapangan** [comment]
Looks good now!

**Comment by tarekait1996** [comment]
Updated the readme with narra's name! Nice catch everyone!

**Comment by jayohanna** [comment]
Looks good

**Comment by EtienneBerube** [comment]
Could Merge! The honor is your's Tarek

**Comment by paulMoose** [comment]
Looks good!

**Comment by a-paggabao** [comment]
awesome!

**Pull request merged**
